INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, ATIVO) VALUES (-1,'BANANA', 1000, TRUE);
INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, ATIVO) VALUES (-2,'LARANJA', 200, TRUE);
INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, ATIVO) VALUES (-3,'MANGA', 500, TRUE);
